name: CI

on:
  pull_request:

env:
  BUILDER_IMAGE: hstreamdb/logdevice-builder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-
          restore-keys: |
            ${{ runner.os }}-

      - name: build 
        run: |
          docker build . -f docker/Dockerfile_mbuild.builder --tag $BUILDER_IMAGE
